version: '3.5'

services:
  minecraft-server:
    ports:
      - '25565:25565'

    volumes:
      - './data:/data'

    environment:
      EULA: 'TRUE'
      SERVER_NAME: 'Test World'
      VERSION: '1.20.1'
      ONLINE_MODE: 'false'
      ENABLE_COMMAND_BLOCK: 'true'
      ENABLE_AUTOPAUSE: 'true'
      MAX_TICK_TIME: -1
      SPAWN_PROTECTION: 0
      OPS: |
        amatiasq

    image: itzg/minecraft-server
    container_name: minecraft

    tty: true
    stdin_open: true
    restart: always
